import { Client } from "@/types/client";
export const clientsData: Client[] = [
  {
    id: 1,
    title: "Stripe",
    logo: "/images/brands/stripe.svg",
    logoWhite: "/images/brands/stripe.svg",
    link: "https://stripe.com/",
  },
  {
    id: 2,
    title: "DigitalOcean",
    logo: "/images/brands/digitalocean.svg",
    logoWhite: "/images/brands/digitalocean.svg",
    link: "https://digitalocean.com/",
  },
  {
    id: 3,
    title: "Zoom",
    logo: "/images/brands/zoom.svg",
    logoWhite: "/images/brands/zoom.svg",
    link: "https://zoom.us/",
  },
  {
    id: 4,
    title: "Twilio",
    logo: "/images/brands/twilio.svg",
    logoWhite: "/images/brands/twilio.svg",
    link: "https://twilio.com/",
  },
  {
    id: 5,
    title: "Google Business Profile",
    logo: "/images/brands/google-business-profile.png",
    logoWhite: "/images/brands/google-business-profile.png",
    link: "https://business.google.com/",
  },
  {
    id: 6,
    title: "Zapier",
    logo: "/images/brands/zapier.svg",
    logoWhite: "/images/brands/zapier.svg",
    link: "https://zapier.com/",
  },
  {
    id: 7,
    title: "Namecheap",
    logo: "/images/brands/namecheap.svg",
    logoWhite: "/images/brands/namecheap.svg",
    link: "https://namecheap.com/",
  },
  {
    id: 8,
    title: "Mailgun",
    logo: "/images/brands/mailgun.svg",
    logoWhite: "/images/brands/mailgun.svg",
    link: "https://mailgun.com/",
  },
  {
    id: 9,
    title: "Vercel",
    logo: "/images/brands/vercel.svg",
    logoWhite: "/images/brands/vercel.svg",
    link: "https://vercel.com/",
  },
  {
    id: 10,
    title: "OpenAI",
    logo: "/images/brands/openai.svg",
    logoWhite: "/images/brands/openai.svg",
    link: "https://openai.com/",
  },
];
